default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: practice_app_development

test:
  <<: *default
  database: practice_app_test

production:
  <<: *default
  database: practice_app_production
  username: practice_app
  password: <%= ENV['PRACTICE_APP_DATABASE_PASSWORD'] %>